# Generated by Django 5.1.7 on 2025-03-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_reconciliationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slicer_new', models.TextField(blank=True, null=True)),
                ('category_new', models.TextField(blank=True, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cat_list_c', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.catlistc')),
                ('cat_list_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.catlistd')),
                ('slicer_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.slicerlist')),
            ],
            options={
                'db_table': 'reconciliation',
            },
        ),
        migrations.DeleteModel(
            name='ReconciliationData',
        ),
    ]
