# Generated by Django 5.1.7 on 2025-03-28 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_reconciliation_delete_reconciliationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='sales_data',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.salesdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
