# Generated by Django 5.1.7 on 2025-03-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_reconciliation_sales_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reconciliation',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
