# Generated by Django 5.1.7 on 2025-04-28 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_reconciliation_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slicer_list', models.CharField(max_length=255)),
                ('cat_list_d', models.CharField(max_length=255)),
                ('cat_list_c', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='cat_list_c',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='cat_list_d',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='slicer_list',
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='category_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.categorymapping'),
        ),
        migrations.DeleteModel(
            name='CatListC',
        ),
        migrations.DeleteModel(
            name='CatListD',
        ),
        migrations.DeleteModel(
            name='SlicerList',
        ),
    ]
